### ISSUE TITLE
Time Zone Corrections

### ISSUE THREAD

**Issue by netiony** [OxWearables/asleep#23]
Is there any chance you could add time zone correction argument(s) similar to GGIR/Accelerometer? Some of our watches were improperly configured, so their time zones need adjusted. 

Thanks!

**Comment by angerhang** [comment]
> Is there any chance you could add time zone correction argument(s) similar to GGIR/Accelerometer? Some of our watches were improperly configured, so their time zones need adjusted.
> 
> Thanks!

@netiony thanks for raising this issue. I just came back from annual leave. Will aim to add this feature by the end of the week. Will give you an update once it is done :D

**Comment by angerhang** [comment]
> Is there any chance you could add time zone correction argument(s) similar to GGIR/Accelerometer? Some of our watches were improperly configured, so their time zones need adjusted.
> 
> Thanks!

Hey @netiony  I probably won't have the time to do it the same that GGIR is doing it in the short term but I have included a flag where you can specify how many hours of times shift that you want for the generated data e.g. `--time_shift=-3`. This should do the trick as well as you know the time difference between your configured time zone and desired time zone :D
