### ISSUE TITLE
torch.cat(): expected a non-empty list of Tensors

### ISSUE THREAD

**Issue by jasonrussell34** [OxWearables/asleep#33]
This is very interested work, and we are interested in using the algorithm with some of our actigraphy data but have been running into an error. We are using .gt3x files and when running the code, the initial steps seem to work and a handful of outputs are produced: a raw csv, an info JSON file and 2 NPY files (data2model and times), but we then get the error: RuntimeError: torch.cat(): expected a non-empty list of Tensors.

Are you able to advise what the issue may be?

**Comment by angerhang** [comment]
> This is very interested work, and we are interested in using the algorithm with some of our actigraphy data but have been running into an error. We are using .gt3x files and when running the code, the initial steps seem to work and a handful of outputs are produced: a raw csv, an info JSON file and 2 NPY files (data2model and times), but we then get the error: RuntimeError: torch.cat(): expected a non-empty list of Tensors.
> 
> Are you able to advise what the issue may be?

Hey @jasonrussell34 thanks for your interest in our work. 

Could you provide a sample test file for gt3x, the command you used and the output error log.

**Comment by jasonrussell34** [comment]
[asleep output.txt](https://github.com/OxWearables/asleep/files/12306108/asleep.output.txt)

I've attached a text file with the console output; I was using the command; get_sleep 2005.gt3x

All our actigraphy files are currently study files, so I will generate a dummy file on me over the weekend; I should be able to share that early next week.

**Comment by jasonrussell34** [comment]
@angerhang - do you have an email I can share the gt3x file to? GitHub doesn't support the transfer of gt3x files. Thanks, Jason

**Comment by jasonrussell34** [comment]
Alternatively occured to me a box share may work - let me know if you can't access this: https://vanderbilt.box.com/s/zyw2uodf8pol1qopnkmoqwm8vhrszmwv

**Comment by angerhang** [comment]
> Alternatively occured to me a box share may work - let me know if you can't access this: https://vanderbilt.box.com/s/zyw2uodf8pol1qopnkmoqwm8vhrszmwv

Thanks for sharing Jason. I just came back from my annual leave, will aim to take a look in the coming days.

**Comment by jasonrussell34** [comment]
@angerhang, have you had any luck in chasing down the bug as yet?

**Comment by angerhang** [comment]
> @angerhang, have you had any luck in chasing down the bug as yet?

Thanks for reporting the issue and providing us with the test data @jasonrussell34 . The good news is that I could replicate the error 

```
Traceback (most recent call last):
  File "/Users/hangy/opt/miniconda3/envs/test_asleep_env/bin/get_sleep", line 8, in <module>
    sys.exit(main())
  File "/Users/hangy/opt/miniconda3/envs/test_asleep_env/lib/python3.8/site-packages/asleep/get_sleep.py", line 279, in main
    master_acc, master_npids) = get_sleep_windows(data2model, times, args)
  File "/Users/hangy/opt/miniconda3/envs/test_asleep_env/lib/python3.8/site-packages/asleep/get_sleep.py", line 139, in get_sleep_windows
    window_pred = sleep_window_detector.predict(data_channel_last)
  File "/Users/hangy/opt/miniconda3/envs/test_asleep_env/lib/python3.8/site-packages/asleep/models.py", line 195, in predict
    _, y_pred, _ = sslmodel.predict(
  File "/Users/hangy/opt/miniconda3/envs/test_asleep_env/lib/python3.8/site-packages/asleep/sslmodel.py", line 148, in predict
    true_list = torch.cat(true_list)
RuntimeError: torch.cat(): expected a non-empty list of Tensors
```

The bad news is that I am not sure what causes the issue. Will investigate further.

**Comment by angerhang** [comment]
Just identified the issue as the prediction function seemed to assume label y is available even for unlabelled data. A fix is on its way.

**Comment by angerhang** [comment]
Thanks for being patient again. If you update to the latest asleep 0.4.4, you should be able to run without issues. Let me know if you have any other questions 👯

**Comment by jasonrussell34** [comment]
Awesome - Thank you!

**Comment by jasonrussell34** [comment]
Hey @angerhang  - I have come up against another issue. It is working great for about 80% of files, but for some I am getting this error: TypeError: expected np.ndarray (got list). 

One of the files that produced this was the JR001.gt3x - I've attached the full txt output below, let me know if you have any thoughts. Thanks!

[Inconsistent error.txt](https://github.com/OxWearables/asleep/files/12771929/Inconsistent.error.txt)

**Comment by faberto** [comment]
> Alternatively occured to me a box share may work - let me know if you can't access this: https://vanderbilt.box.com/s/zyw2uodf8pol1qopnkmoqwm8vhrszmwv

Unable to run this with the current version. Same error as described in the initial post of this issue.
