### ISSUE TITLE
TypeError: expected np.ndarray (got list).

### ISSUE THREAD

**Issue by jasonrussell34** [OxWearables/asleep#36]
Hey @angerhang , the last bug fix worked well. I have now got through the processing on all our files and have come across a couple of additional issues.

For a number of files we are getting the type error in the title - I have attached a txt output of this. This happens in the JR001.gt3x file that you had previously.

I am also seeing a less frequent issue where I run on a given file and it appears to start, produces the text Saving files to dir: outputs/'filename', but then stops processing and waits for the next file input. It appears that it does not successfully read the file. I didn't know if you may have come across this/had any immediate thoughts? If not I would plan to analyse all the data we can, if we can fix the type error issue and then if all is looking good with those work through everything we need to, to get some of our study files to you to see if you can replicate.

[Inconsistent error.txt](https://github.com/OxWearables/asleep/files/12820223/Inconsistent.error.txt)

**Comment by czisou** [comment]
@angerhang this bug can also be reproduced eg. with "ukb/accelerometer/group1/4103167_90001_0_0.cwa.gz".

**Comment by angerhang** [comment]
Thanks both for reporting @jasonrussell34 and @czisou, this will be a priority bug to fix. Cause is unknown at the moment but I will spend one day next week to resolve all the outstanding priority technical debts.

@jasonrussell34 it seems that we can replicate this error so no need for data transfer yet but appreciate the help :D

**Comment by jasonrussell34** [comment]
Thanks @angerhang !
