### ISSUE TITLE
IndexError: index 0 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by czisou** [OxWearables/asleep#42]
I believe it is simply a matter of better error handling.

This bug can be reproduced e.g. with the file "ukb/accelerometer/group1/4380443_90001_0_0.cwa.gz"

See attached file for the log.
[index_error_log.txt](https://github.com/OxWearables/asleep/files/13072492/index_error_log.txt)

**Comment by angerhang** [comment]
A large number of UKB repeats have the same error. Not sure what causes this and if there are multiple causes.

Going to investigate the cause on two participants: `3338212_90001_1_0` and `1120527_90001_1_0`

With current log files stored at: `tnk541-46895854_1499.log` and `tnk541-46895854_685.log`
