### ISSUE TITLE
IndexError: positional indexers are out-of-bounds

### ISSUE THREAD

**Issue by czisou** [OxWearables/asleep#43]
I believe this is also a matter of better error handling.

This bug can be reproduced e.g. with the file "ukb/accelerometer/group5/3801805_90001_0_0.cwa.gz"

See attached file for the log.
[index_error_log.txt](https://github.com/OxWearables/asleep/files/13117168/index_error_log.txt)

**Comment by LeandroCasiraghi** [comment]
Hi, I've been having the exact same issue on different computers (both on Windows and Linux systems). 
Now trying to run _asleep_ on a fresh Windows 10 install on an Anaconda virtual environment with _openjdk_ 11.0.13 and _python_ 3.9.18, and getting the same. 
Not sure what additional information I could supply to help figure this out.

**Comment by angerhang** [comment]
> Now trying to run _asleep_ on a fresh Windows 10 install on an Anaconda virtual environment with _openjdk_ 11.0.13 and _python_ 3.8.18, and getting the same.

weird, this should have been sorted. Could you provide me with a sample file?

**Comment by LeandroCasiraghi** [comment]
Hi! Of course, here's one:
https://drive.google.com/file/d/1-8D2SXm_B6NCvTh_3cCtEl2ZIM0PGNTc/view?usp=sharing

I do have **one** computer in which I can run asleep with no issues; but I haven't been able to get it to work anywhere else. 
I'm trying to set up a new computer in my lab for people to be able to work with their AX3 data, and having the same issue I had elsewhere in other computers, Win or Linux based.

**Comment by LeandroCasiraghi** [comment]
Coming back with a weirder (if that´s even possible) update on this issue:
Yesterday I run _asleep_ on a bunch of files in the lab computer where it works with no problems. Then I moved to a second set of files (same AX3 devices, same participants, but recorded just after the others) and started getting the "indexers out of bounds" error...

Now, for more weirdness, I'm running _asleep_ in my personal laptop at home... and it's running on both set of files with no errors. I'm trying to come up with theories about where this error is arising from, but I have no clue. 
Maybe date or time formats, being read differently on different systems? This wouldn't explain why one computer would be able to process one set of files and not the other.
Something to do with the size of files and RAM? This also wouldn't explain why my lab computer wouldn't do it while my personal laptop does (both are 16gb DDR4).

**Comment by angerhang** [comment]
> Now, for more weirdness, I'm running _asleep_ in my personal laptop at home... and it's running on both set of files with no errors. I'm trying to come up with theories about where this error is arising from, but I have no clue.

Hey @LeandroCasiraghi thanks for getting in touch again. I suspect it might be due to your local python environment. If you verify that all of your systems have the same python version and dependencies, then it should work.

By any chance if you are using any virtual environment to help you manage your dependencies, if you haven't. That might be a good thing to try.

**Comment by LeandroCasiraghi** [comment]
@angerhang thanks for the reply. Indeed, I'm working on virtual environments on all devices. 
I will check the matching of dependencies on each computer and see what comes out and report it here.

**Comment by BernieVA** [comment]
I had the same exception and did some digging and found out day interval calculation had a bug, the first interval starts with at noon of the previous day and ends at noon of first day of wearing. However, if you started to wear after noon of the first day, there is no data in the first interval. 
What I did is to add the following code to  the file    "\AppData\Local\anaconda3\envs\asleep\Lib\site-packages\asleep\sleep_window.py"

after line 272:

    if start_date.hour < 12:
        my_day_start = start_date.replace(
            hour=12, minute=0, second=0, microsecond=0)
        my_day_start = my_day_start - timedelta(hours=24)
    else:
        my_day_start = start_date.replace(
            hour=12, minute=0, second=0, microsecond=0)

it worked then.

**Comment by angerhang** [comment]
> I had the same exception and did some digging and found out day interval calculation had a bug, the first interval starts at noon of the previous day and ends at noon of the first day of wearing. However, if you started to wear after noon of the first day, there is no data in the first interval. What I did is to add the following code to the file "\AppData\Local\anaconda3\envs\asleep\Lib\site-packages\asleep\sleep_window.py"
> 
> after line 272:
> 
> ```
> if start_date.hour < 12:
>     my_day_start = start_date.replace(
>         hour=12, minute=0, second=0, microsecond=0)
>     my_day_start = my_day_start - timedelta(hours=24)
> else:
>     my_day_start = start_date.replace(
>         hour=12, minute=0, second=0, microsecond=0)
> ```
> 
> it worked then.

Thanks for the clarification. Indeed this is the expected behaviour. If you have the time to make a PR, happy to take a look :D

**Comment by LeandroCasiraghi** [comment]
Hi all, again. I updated the package to the latest version today on my personal and encountered this error on a file I had processed succesfully just yesterday. I'm trying to implement @BernieVA 's solution now, but I'm seeing that line 272 is not a clear position anymore, after the last update. Would you clarify where to modify the sleep_window.py file to make it work now?
Thanks!

**Comment by BernieVA** [comment]
def get_day_intervals(start_date, end_date, date_format):
    # 1. Get day intervals

    day_intervals = []
    day_end_str = "1990-01-01 09:47:50.439000"
    my_day_end = pd.to_datetime(day_end_str, format=date_format)

    if start_date.hour < 12:
    my_day_start = start_date.replace(
        hour=12, minute=0, second=0, microsecond=0)
    my_day_start = my_day_start - timedelta(hours=24)
  else:
    my_day_start = start_date.replace(
        hour=12, minute=0, second=0, microsecond=0)


From: LeandroCasiraghi ***@***.***>
Sent: Friday, July 12, 2024 5:25 PM
To: OxWearables/asleep ***@***.***>
Cc: Gan, Qiwei ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [OxWearables/asleep] IndexError: positional indexers are out-of-bounds (Issue #43)


Hi all, again. I updated the package to the latest version today on my personal and encountered this error on a file I had processed succesfully just yesterday. I'm trying to implement @BernieVA<https://github.com/BernieVA> 's solution now, but I'm seeing that line 272 is not a clear position anymore, after the last update. Would you clarify where to modify the sleep_window.py file to make it work now?
Thanks!

-

**Comment by angerhang** [comment]
@LeandroCasiraghi and @BernieVA thanks for reporting. Indeed, a couple of our members have also reported the same error which seems to be strange. I suspect it might because some dependencies have changed to make new installation break. I will investigate this issue tomorrow and provide a patch

**Comment by angerhang** [comment]
Hey all, I believe the recent PR should have fixed this issue. 

You could test it out with the least release
```
 pip install --upgrade asleep
```

If the issue still persists, please provide me with a sample file. Thanks for all of your feedback again ;D @LeandroCasiraghi @BernieVA @aidanacquah
